### ISSUE TITLE
The Melpa pkgspec needs to be updated

### ISSUE THREAD

**Issue by achinhorn** [waymondo/projector.el#6]
Github 404's since the provided link is
`https://github.com/waymondo/projector`, instead of
`https://github.com/waymondo/projector.el`

**Comment by waymondo** [comment]
What steps do you encounter the 404 with? I am able to install the package with `package.el` and `straight.el` from MELPA. The MELPA recipe specifies the repo as "waymondo/projector.el"

I updated the URL in the header of `projector.el`, which incorrectly did not include the `.el`, if your installation was failing from that somehow. Let me know if it is still not working for you.

**Comment by achinhorn** [comment]
Sorry, I see now I was ambiguous, but it appears that you've fixed it. I meant the provided Homepage. 

Even though it doesn't effect installation directly, I thought the package would benefit by submitting the issue considering how important (I at least) rely on the provided home page to validate package candidates.

Closing.

**Comment by waymondo** [comment]
No problem, thanks for raising the issue. Hope the package is helpful to you!
